//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Pjt_Shopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Compare
    {
        [DataMember]
        public int Compare_Id { get; set; }
        [DataMember]
        public Nullable<int> User_Id { get; set; }
        [DataMember]
        public Nullable<int> Prod_Id { get; set; }
        [DataMember]
        public Nullable<int> Category_Id { get; set; }
        [DataMember]

        public virtual Category Category { get; set; }
        [DataMember]
        public virtual Product Product { get; set; }
        [DataMember]
        public virtual User User { get; set; }
    }
}
