//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Final_Shopping_dbEntities : DbContext
    {
        public Final_Shopping_dbEntities()
            : base("name=Final_Shopping_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Retailer> Retailers { get; set; }
        public virtual DbSet<Update_Products> Update_Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
    
        public virtual ObjectResult<GetCart_Result> GetCart(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCart_Result>("GetCart", useridParameter);
        }
    
        public virtual ObjectResult<GetCartItems_Result> GetCartItems(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItems_Result>("GetCartItems", useridParameter);
        }
    
        public virtual ObjectResult<GetUserDetails_Result> GetUserDetails(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserDetails_Result>("GetUserDetails", uidParameter);
        }
    
        public virtual ObjectResult<GetWishItem_Result> GetWishItem(Nullable<int> prodid)
        {
            var prodidParameter = prodid.HasValue ?
                new ObjectParameter("prodid", prodid) :
                new ObjectParameter("prodid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWishItem_Result>("GetWishItem", prodidParameter);
        }
    
        public virtual ObjectResult<GetWishlist_Result> GetWishlist(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWishlist_Result>("GetWishlist", useridParameter);
        }
    
        public virtual ObjectResult<retailer_revdetails_Result> retailer_revdetails(Nullable<int> retail_id)
        {
            var retail_idParameter = retail_id.HasValue ?
                new ObjectParameter("retail_id", retail_id) :
                new ObjectParameter("retail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<retailer_revdetails_Result>("retailer_revdetails", retail_idParameter);
        }
    
        public virtual ObjectResult<sp_GetAllCategoryfromdb_Result> sp_GetAllCategoryfromdb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllCategoryfromdb_Result>("sp_GetAllCategoryfromdb");
        }
    
        public virtual ObjectResult<sp_GetAllPdtfromdb_Result> sp_GetAllPdtfromdb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllPdtfromdb_Result>("sp_GetAllPdtfromdb");
        }
    
        public virtual ObjectResult<sp_GetOnePdtfromdb_Result> sp_GetOnePdtfromdb(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetOnePdtfromdb_Result>("sp_GetOnePdtfromdb", idParameter);
        }
    
        public virtual ObjectResult<sp_getOrders_Result> sp_getOrders(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOrders_Result>("sp_getOrders", useridParameter);
        }
    
        public virtual ObjectResult<sp_getOrdersfromCart_Result> sp_getOrdersfromCart(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOrdersfromCart_Result>("sp_getOrdersfromCart", useridParameter);
        }
    
        public virtual ObjectResult<sp_Pdts_Of_One_Category_Result> sp_Pdts_Of_One_Category(Nullable<int> cat_id)
        {
            var cat_idParameter = cat_id.HasValue ?
                new ObjectParameter("cat_id", cat_id) :
                new ObjectParameter("cat_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Pdts_Of_One_Category_Result>("sp_Pdts_Of_One_Category", cat_idParameter);
        }
    
        public virtual ObjectResult<sp_PdtsOfOneCategoryfromdb_Result> sp_PdtsOfOneCategoryfromdb(Nullable<int> cat_id)
        {
            var cat_idParameter = cat_id.HasValue ?
                new ObjectParameter("cat_id", cat_id) :
                new ObjectParameter("cat_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PdtsOfOneCategoryfromdb_Result>("sp_PdtsOfOneCategoryfromdb", cat_idParameter);
        }
    }
}
