//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Order
    {
        [DataMember]
        public int Order_Id { get; set; }
        [DataMember]
        public Nullable<int> User_id { get; set; }
        [DataMember]
        public Nullable<int> Prod_id { get; set; }
        [DataMember]
        public Nullable<decimal> Prod_Price { get; set; }
        [DataMember]
        public Nullable<int> Prod_Quantity { get; set; }
        [DataMember]
        public Nullable<int> Retail_id { get; set; }
       

        public virtual Product Product { get; set; }
        public virtual Retailer Retailer { get; set; }
        public virtual User User { get; set; }
    }
}
